name: Update GitHub Stats
on:
  schedule:
    - cron: '0 * * * *' # Updates hourly
  workflow_dispatch:

jobs:
  update-stats:
    runs-on: ubuntu-latest
    steps:
      - name: Refresh Stats
        run: |
          curl -s "https://streak-stats.demolab.com?user=Sagarkumar49&theme=github-dark" > /dev/null
          curl -s "https://github-readme-stats.vercel.app/api?username=Sagarkumar49" > /dev/null
